blog/urls.py
# WE CREATED THIS FILE FOR URLS #


app_name = 'blog'       # for blog.html file(read there)

from django.urls import path
from . import views     # the . means current directory

urlpatterns = [
    # path('', views.home, name="home"),  # so we created a homepage here now if we want to show project stuff like project objects (java course , python course)
    path('blog/', views.blog_allUrls, name='blogUrls'),      #localhost:8000/blog/blog
    path('<int:blog_id>', views.detail, name='detail'),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path , include

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),  # so we created a homepage here now if we want to show project stuff like project objects (java course , python course)
    path('blog/', include('blog.urls')),    # so in here we include all the urls in blog project to have access to them in here too => localhost:8000/blog/blog # for this we needed to create a urls.py which contains the blog urls and connect them to views in blog folder by importing them and making a templates
]


# we added this to get MEDIA_ROOT and MEDIA_URL
from django.conf.urls.static import static      # we added this here
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # we added this: so when we want to get the file from user
                # and save it in our MEDIA_URL and MEDIA_ROOT we need to add this line too

blog/models.py
from django.db import models

# Create your models here.

class BlogModel(models.Model):

    linkTitle = models.CharField(max_length=100)
    shortInfo = models.TextField()
    date = models.DateField(auto_now_add=True)
    url = models.URLField(blank=True)       # if we dont want to make url for the new project created in admin section we add blank=True

portfolio/models.py
from django.db import models

# Create your models here.

# for working with data base:

class Project(models.Model):

    # when ever you want to add a property or a field, use the models module

    title = models.CharField(max_length=100)        # using model field django to create a string
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')    # for this you need to install pillow module
    url = models.URLField(blank=True)

    # after creating our fields or attributes we need to add these to data base by using: python manage.py migrate and python manage.py makemigrations
    
    
    # so if you look at admin page and go to projects you cant see the projects name, this will shows the projects name 
    # you dont need to migrate or makemigrate here because the function has nothing to do with the data base. there are attributes and fields that changes and have to migrate them
    # DO THIS FOR BLOG PROJECTS TOO!
    # be careful to create this method in class not outside!!!!!
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from .models import BlogModel       # we added
from django.shortcuts import get_object_or_404  # we added

# Create your views here.


def blog_allUrls(request):

    blog = BlogModel.objects.all()
    # blog = BlogModel.objects.order_by('-id')[:2]  # Retrieves 5 most recent objects based on their IDs

    return render(request, "blog/blog_allUrls/blog.html", {"blogs": blog})


def detail(request, blog_id):
    # For finding an object we can use primary key(any created object has a special key number for accessing)
    # get_object_or_404 should be imported (from django.shortcuts import get_object_or_404) for finding an object
    # get_object_or_404(models.py class name, pk=)
    blog = get_object_or_404(BlogModel, pk=blog_id)     # get_object_or_404() is a method which check if our BlogModel site is available or not; pk(primary key) In Django models, each model has a primary key field that uniquely identifies each record in the database table.
    
    return render(request, 'blog/blog_allUrls/detail.html', {'id':blog_id, 'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.

def home(request):

    projects = Project.objects.all()   # this line will get all the objects which we created on server and shows it in homepage

    return render(request, "portfolio/homepage.html", {"projects": projects})     # we sent a dictionary which contains all projects

blog/templates/blog/blog_allUrls/blog.html
{% extends 'portfolio/base.html' %}     <!--i've explained this in homepage.html file-->

{% block content %}

<h1>hello blog part</h1>


{{ blogs }}
<br><br><br>    
<h2>mehran has writtern {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>     <!--blog.count counts the number of blogs, {{ blogs.count|pluralize }} shows if blog need an s at the end or not-->   

<!--here we get all the blogs and address them with their ids-->

{% for b in blogs %}

    <a href="{% url 'blog:detail' b.id %}"><h2>{{b.linkTitle}}</h2></a>     <!--the blog in blog:detail refers to urls.py app_name = 'blog' => this make the urls more certain and if we not make it certain it may open another page-->
    {{ b.date}} <br>
    {{ b.date|date:'D, N j Y' }}            <!--see all the django date format document https://docs.djangoproject.com/en/5.1/ref/templates/builtins/#date -->

    <!-- <p><h3>{{ b.shortInfo }}</h3></p> <br>  -->
    <p><h3>{{ b.shortInfo|safe|truncatewords:50 }}</h3></p> <br>     <!--|truncatewords:10 will shows only 10 word of the Info: we use it when the info is big; safe is for formatting the text, we write a text in admin and use some html tags like <b></b> and then put safe in here to show the changes-->
    <!--the |striptags disables all the html tags we used in admin -->
    {% endfor %}


{% endblock %}

blog/templates/blog/blog_allUrls/detail.html
{% extends 'portfolio/base.html' %}     <!--i've explained this in homepage.html file-->

{% block content %}

{{ id }} <br>

<h1>{{ blog.linkTitle }}</h1>
<br>
<h2>{{ blog.date|date:'F jS Y'}}</h2>
<br>

{{ blog.shortInfo|safe }}   <!--\safe for applying all the tags which are used in shortInfo in admin section-->


{% endblock %}

portfolio/templates/portfolio/base.html
<!--you can name this file what ever you want-->

<!--the reason we created this file is if we want to style our pages we dont have to rewrite the codes, we just simply use this file to use the navbar or else.
so what we do here is we create a template here and extend it to another pages-->

<!--below codes are from bootstrap site -->


<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>



      <!--the top codes are the nav and the html codes for site-->
      <!--here we want the blogs or projects we created come from -->
      {% block content  %}{% endblock %}





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/homepage.html
{% extends 'portfolio/base.html' %} <!--first we extend the file(template) which we create to shows some stuff like navbar and html and etc.-->

{% block content %}         <!--then we start a block with block and use content variable as we have defined it in our base.html file after navbar
                            we close our block after our homepage codes with endblock-->
                            <!--Another important thing is the variable name(content in here) should be as same as the name of the variable in base.html file-->



    
    <h1>welcome to learn code by mehran</h1>

<!--the static url in setting is related to this section so if you want to create a folder for this subject you have to create it with exact name of given value for static url in setting file-->
{% load static %}
<img src="{% static 'portfolio/backiee-269692.jpg' %}" length="1000" width="1000" style="display: block; margin: 0 auto">      <!--when ever you want to use static in your codes you have to add {% load static %}-->

<a href="{% static 'portfolio/resume.pdf' %}">Resume</a><br><br>      <!--everyone can download your resume pdf or another thing here-->

<a href="{% url 'blog:blogUrls' %}">Blogs</a>       <!--the blog:blogUrls => we used blog app name in blog urls file and get the blog page variable name-->

<h2>purpose</h2>
<p>in this site we have a lot of courses which makes you a professional programmer</p>

{{ projects }}
<br><br>

{% for i in projects %}


{% if i.url %}                                          <!--checks if project has an url or not, if has one shows the title and url-->
    <a href="{{ i.url }}"><h2>{{ i.title }}</h2></a>
{% endif %}

    <p>{{ i.description }}</p>

    {{ i.image }}<br>   <!--shows the image url-->
    <img src="{{ i.image.url }}" height=100 width=100>  <!--shows the image-->

    

{% endfor %}



{% endblock %}